### ISSUE TITLE
Does not install completely

### ISSUE THREAD

**Issue by UnixMover** [poucotm/Log-Highlight#7] opened 2017-06-15 15:18 UTC
When using the package manager to install, the menu items is installed as it is selectable; however the package directory is never made. Downloading the package and placing it into the packages directory and insuring that the name is correct (remove hyphen from downloaded package), the log receives highlighting. Even though this is a +, the features -- like double clicking on links -- does not work. There is no pane (ctrl+12). It just doesn't work.

I have tried it on the latest released (licensed) and the latest beta build -- both have the same results.

From the console:
   reloading plugin Log Highlight.Log Highlight

From Build:
Creating a error in the code;
       from ..utils import indexable, check_random_state, safe_indexing
   ValueError: attempted relative import beyond top-level package       <<<---- this is colored red now

Turning on sublime logging:
     File "C:\Users\user1\AppData\Roaming\Sublime Text 3\Packages\Log Highlight\Log Highlight.py", line 410, in on_activated_async
        if not view.settings().get('syntax').endswith('Log Highlight.tmLanguage'):
   AttributeError: 'NoneType' object has no attribute 'endswith'

System:
    Windows 10
        Running as unprivileged user
    Anaconda (latest)
    Licensed Sublime Text 3 (beta installed currently, does not work on public release)

**Comment by poucotm** [comment] 2017-06-16 13:49
Hi,

Log Highlight package will be installed under, "...Sublime Text 3\Installed
Packages". If it doesn't work (double click, summary panel,...), it means
that there are run-time errors.
I updated the codes (v1.3.2) to prevent the error - "AttributeError:
'NoneType' object has no attribute 'endswith'". But I'm not sure it can
help you.
Unfortunately, I can not test in Windows 10 and I'm using Sublime Text
Build 3126. Please, check with v1.3.2 and let me know



2017-06-16 0:18 GMT+09:00 UnixMover <notifications@github.com>:

**Comment by rwese** [comment] 2017-07-26 04:50
Installed today via package manager, works as intended on Win 7, x64.

**Comment by poucotm** [comment] 2017-07-26 09:14
That is great!

2017년 7월 26일 수요일, René<notifications@github.com>님이 작성한 메시지:

**Closed** 2017-10-05 12:00 UTC
